name: construction_technect
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter

  flutter_svg: ^2.2.0
  intl_phone_field: ^3.2.0
  dotted_border: ^3.1.0
  get: ^4.7.2
  responsive_sizer: ^3.3.0+1  
  pin_code_fields: ^8.0.1
  auto_route: ^10.1.2
  get_storage: ^2.1.1
  http: ^1.5.0
  connectivity_plus: ^7.0.0
  google_maps_flutter: ^2.6.1
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  file_picker: ^10.3.3
  image_picker: ^1.2.0
  cached_network_image: ^3.3.1
  intl: ^0.20.2
  lottie: ^3.3.1
  gap: ^3.0.1
  url_launcher: ^6.2.2
  timer_count_down: ^2.2.2
  flutter_image_compress:
  path_provider:
  youtube_player_flutter: ^9.1.2



dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^2.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/animation/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
        - asset: assets/fonts/Lato-Italic.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
        - asset: assets/fonts/Roboto/Roboto-ThinItalic.ttf
        - asset: assets/fonts/Roboto/Roboto-ExtraLight.ttf
        - asset: assets/fonts/Roboto/Roboto-ExtraLightItalic.ttf
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
        - asset: assets/fonts/Roboto/Roboto-LightItalic.ttf
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Italic.ttf
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto/Roboto-MediumItalic.ttf
        - asset: assets/fonts/Roboto/Roboto-SemiBold.ttf
        - asset: assets/fonts/Roboto/Roboto-SemiBoldItalic.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto/Roboto-BoldItalic.ttf
        - asset: assets/fonts/Roboto/Roboto-ExtraBold.ttf
        - asset: assets/fonts/Roboto/Roboto-ExtraBoldItalic.ttf
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
        - asset: assets/fonts/Roboto/Roboto-BlackItalic.ttf
    - family: Geometric
      fonts:
        - asset: assets/fonts/Geometric/Geometric 706 Medium.otf
       
