name: construction_technect
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter

  flutter_svg: ^2.2.0
  intl_phone_field: ^3.2.0
  dotted_border: ^3.1.0
  get: ^4.7.2
  responsive_sizer: ^3.3.0+1  
  pin_code_fields: ^8.0.1
  auto_route: ^10.1.2
  get_storage: ^2.1.1
  http: ^1.5.0
  connectivity_plus: ^7.0.0
  google_maps_flutter: ^2.6.1
  google_places_flutter: ^2.1.1
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  file_picker: ^10.3.3
  image_picker: ^1.2.0
  cached_network_image: ^3.3.1
  intl: ^0.20.2
  lottie: ^3.3.1
  gap: ^3.0.1
  url_launcher: ^6.2.2
  timer_count_down: ^2.2.2
  share_plus: ^12.0.0
  flutter_image_compress:
  path_provider:
  youtube_player_flutter: ^9.1.2
  fl_chart: ^1.1.1
  readmore: ^3.0.0
  month_picker_dialog: ^6.5.0
  open_filex: ^4.7.0
  video_player: ^2.10.0
  video_compress: ^3.1.3
  firebase_core: ^4.2.0
  google_sign_in: ^7.2.0
  firebase_auth: ^6.1.1
  upgrader: ^11.5.0
  app_settings: ^6.1.1
  flutter_offline: ^6.0.0
  socket_io_client: ^3.1.2
  record: ^6.1.2
  just_audio: ^0.10.5
  table_calendar: ^3.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^2.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/icons/
    - assets/images/bg/
    - assets/images/png/
    - assets/images/png/feature/
    - assets/images/png/role/
    - assets/images/svg/
    - assets/animation/

  fonts:
    - family: SpaceGrotesk
      fonts:
        - asset: assets/fonts/SpaceGrotesk/SpaceGrotesk-Regular.ttf
        - asset: assets/fonts/SpaceGrotesk/SpaceGrotesk-Bold.ttf
        - asset: assets/fonts/SpaceGrotesk/SpaceGrotesk-Light.ttf
        - asset: assets/fonts/SpaceGrotesk/SpaceGrotesk-Medium.ttf
        - asset: assets/fonts/SpaceGrotesk/SpaceGrotesk-SemiBold.ttf

