name: construction_technect
description: A new Flutter project.
publish_to: none
version: 1.0.0+6
environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  app_settings: ^6.1.1
  auto_route: ^10.1.2
  cached_network_image: ^3.3.1
  carousel_slider: ^5.1.1
  connectivity_plus: ^7.0.0
  cupertino_icons: ^1.0.8
  dotted_border: ^3.1.0
  file_picker: ^10.3.3
  firebase_auth: ^6.1.1
  firebase_core: ^4.2.0
  firebase_messaging: ^16.1.0
  fl_chart: ^1.1.1
  flutter_image_compress: null
  flutter_local_notifications: ^19.5.0
  flutter_offline: ^6.0.0
  flutter_slidable: ^4.0.3
  flutter_svg: ^2.2.0
  gap: ^3.0.1
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  get: ^4.7.2
  get_storage: ^2.1.1
  google_maps_flutter: ^2.6.1
  google_places_flutter: ^2.1.1
  google_sign_in: ^7.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.5.0
  http_parser: ^4.1.2
  image_picker: ^1.1.2
  intl: ^0.20.2
  intl_phone_field: ^3.2.0
  just_audio: ^0.10.5
  lottie: ^3.3.1
  month_picker_dialog: ^6.5.0
  open_filex: ^4.7.0
  path: ^1.9.0
  path_provider: null
  permission_handler: ^12.0.1
  phone_number_hint: ^0.0.6
  pin_code_fields: ^8.0.1
  readmore: ^3.0.0
  record: ^6.1.2
  responsive_sizer: ^3.3.0+1
  share_plus: ^12.0.0
  sms_autofill: ^2.4.1
  socket_io_client: ^3.1.2
  step_progress: ^2.7.1
  table_calendar: ^3.2.0
  timer_count_down: ^2.2.2
  upgrader: ^11.5.0
  url_launcher: ^6.2.2
  video_compress: ^3.1.3
  video_player: ^2.10.0
  youtube_player_flutter: ^9.1.2
  curved_navigation_bar: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.8.0
flutter:
  uses-material-design: true
  assets:
  - assets/fonts/
  - assets/images/
  - assets/images/icons/
  - assets/images/bg/
  - assets/images/png/
  - assets/images/png/feature/
  - assets/images/png/role/
  - assets/images/svg/
  - assets/animation/
  fonts:
  - family: SpaceGrotesk
    fonts:
    - asset: assets/fonts/SpaceGrotesk/SpaceGrotesk-Regular.ttf
    - asset: assets/fonts/SpaceGrotesk/SpaceGrotesk-Bold.ttf
    - asset: assets/fonts/SpaceGrotesk/SpaceGrotesk-Light.ttf
    - asset: assets/fonts/SpaceGrotesk/SpaceGrotesk-Medium.ttf
    - asset: assets/fonts/SpaceGrotesk/SpaceGrotesk-SemiBold.ttf
